### PR TITLE
Replace proc-macro-error with proc-macro-error2

### LINKED ISSUE #4: proc-macro-error is unmaintained
c.f. https://github.com/rustsec/advisory-db/pull/2057
```
syn_derive> cargo deny check advisories
2024-09-05 23:40:22 [WARN] unable to find a config path, falling back to default config
error[unmaintained]: proc-macro-error is unmaintained
  ┌─ /home/jayvdb/rust/syn_derive/Cargo.lock:1:1
  │
1 │ proc-macro-error 1.0.4 registry+https://github.com/rust-lang/crates.io-index
  │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
  │
  ├ ID: RUSTSEC-2024-0370
  ├ Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0370
  ├ proc-macro-error's maintainer seems to be unreachable, with no commits for 2 years, no releases pushed for 4 years, and no activity on the GitLab repo or response to email.

    proc-macro-error also depends on `syn 1.x`, which may be bringing duplicate dependencies into dependant build trees.

    ## Possible Alternative(s)

    - [proc-macro-error2](https://crates.io/crates/proc-macro-error2)
  ├ Announcement: https://gitlab.com/CreepySkeleton/proc-macro-error/-/issues/20
  ├ Solution: No safe upgrade is available!
  ├ proc-macro-error v1.0.4
    └── syn_derive v0.1.8

advisories FAILED
```

https://crates.io/crates/proc-macro-error2 is the only published replacement so far as I can see.  There are a few other forks around tho.

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/Kyuuhachi/syn_derive/issues/4

### CODE REVIEW

**Comment by jayvdb** [comment]
@Kyuuhachi , as you can see the stats of https://crates.io/crates/proc-macro-error2 are rapidly increasing.

**Comment by kayagokalp** [comment]
Bump on this. There are lot's of crates depending on on this syn_derive crate transitively 👀 proc_macro_error2 has ~800k downloads now

**Comment by Kyuuhachi** [comment]
I'm really sorry about the delay - I've been pretty low on energy lately. But I'll make sure to merge this and push a new version once I'm off work today.

Also wtf, this crate has 11M dls? That's a few orders of magnitude more than I thought it'd get.

**Comment by Kyuuhachi** [comment]
There we go, version 0.2.0 is up. Sorry again for the delay.

**Comment by kayagokalp** [comment]
Great! Thanks for the help 🫡

**Pull request merged**
